'use strict'

module.exports = {
	RECV_CREATE: 'RECV_CREATE',
	RECV_STOP: 'RECV_STOP',
	CREATING: 'CREATING',
	CREATED: 'CREATED',
	NOT_CREATED: 'NOT_CREATED',
	EXITED: 'EXITED',
	START_PULL: 'PULLING',
	END_PULL: 'END PULL',
	ERROR_PULL: 'ERROR IN PULL',
	CREATING_VOLUMES: 'CREATING VOLUMES',
	ERROR_CREATING_VOLUMES: 'ERROR IN CREATING VOLUMES',
	CREATING_CONTAINER: 'CREATING CONTAINER',
	ERROR_CREATING_CONTAINER: 'ERROR CREATING CONTAINER',
	ERROR_CREATING_NETWORK: 'ERROR_CREATING_NETWORK',
	RUNNING: 'RUNNING',
	ERROR: 'ERROR',
	DELETING: 'DELETING',
	DELETED: 'DELETED',
	NOT_PRESENT: 'NOT_PRESENT',
	UNKNOWN: 'UNKNOWN',
}